### ISSUE TITLE
`to_hash` raises ArgumentError

### ISSUE THREAD

**Issue by ged** [jeremyevans/sequel_pg#22] opened 2016-04-11 22:01 UTC
The newest version of `sequel_pg` causes `Sequel::Dataset#to_hash` to raise an `ArgumentError`. Here's a minimal repro case; it requires a `test` Postgres database on localhost that the default user has `CREATE` privileges on:

```
#!/usr/bin/env ruby

gem 'pg', '= 0.18.4'
gem 'sequel', '= 4.33.0'
gem 'sequel_pg', '= 1.6.15'

require 'pg'
require 'sequel'

DB = Sequel.connect( 'postgresql:/test' )

DB << 'DROP TABLE IF EXISTS foo'
DB << 'CREATE TABLE foo ( id serial, name text )'

ds = DB[:foo]
ds.to_hash( :id )
```

Running this in my environment looks like:

```
$ ruby -vd examples/to_hash_breakage.rb
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
Exception `LoadError' at /Users/ged/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems.rb:1222 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/ged/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems.rb:1231 - cannot load such file -- rubygems/defaults/ruby
eval:1: warning: instance variable @ajd not initialized
/Users/ged/.rvm/gems/ruby-2.2.4@[gemset]/gems/sequel_pg-1.6.15/lib/sequel_pg.bundle: warning: method redefined; discarding old yield_hash_rows
/Users/ged/.rvm/gems/ruby-2.2.4@[gemset]/gems/sequel-4.33.0/lib/sequel/adapters/postgres.rb:854: warning: previous definition of yield_hash_rows was here
/Users/ged/.rvm/gems/ruby-2.2.4@[gemset]/gems/sequel_pg-1.6.15/lib/sequel_pg.bundle: warning: method redefined; discarding old fetch_rows_set_cols
/Users/ged/.rvm/gems/ruby-2.2.4@[gemset]/gems/sequel-4.33.0/lib/sequel/adapters/postgres.rb:832: warning: previous definition of fetch_rows_set_cols was here
/Users/ged/.rvm/gems/ruby-2.2.4@[gemset]/gems/sequel-4.33.0/lib/sequel/dataset/query.rb:80: warning: instance variable @columns not initialized
Exception `ArgumentError' at /Users/ged/.rvm/gems/ruby-2.2.4@[gemset]/gems/sequel_pg-1.6.15/lib/sequel_pg/sequel_pg.rb:39 - wrong number of arguments (3 for 1..2)
/Users/ged/.rvm/gems/ruby-2.2.4@[gemset]/gems/sequel-4.33.0/lib/sequel/dataset/actions.rb:718:in `to_hash': wrong number of arguments (3 for 1..2) (ArgumentError)
	from /Users/ged/.rvm/gems/ruby-2.2.4@[gemset]/gems/sequel_pg-1.6.15/lib/sequel_pg/sequel_pg.rb:39:in `to_hash'
	from examples/to_hash_breakage.rb:16:in `<main>'
```

**Comment by jeremyevans** [comment] 2016-04-11 22:11
Thanks for the heads up. I apparently only tested this with the Sequel master branch.  I'll need to push out another version right away that works with the older API.

**Comment by jeremyevans** [comment] 2016-04-11 22:19
The problem is the super call should only be called with two arguments if it doesn't accept more than that.  I think `elsif opts.empty?; super(key_column, value_column)` should work.

This wasn't caught because I dogfood and run all of my applications on the Sequel master branch.  Looks like that isn't a necessarily a great idea in all cases.

I should have 1.6.16 released in a few minutes

**Closed** 2016-04-11 22:24 UTC

**Comment by ged** [comment] 2016-04-11 22:57
You're the best, man! <3
