### ISSUE TITLE
Streaming doesn't work with RDS db

### ISSUE THREAD

**Issue by ollym** [jeremyevans/sequel_pg#38] opened 2020-05-06 08:54 UTC
We're trying to iterate over a very large table (1M+ rows) for a big data migration. The plan was to use streaming to reduce memory usage and make it faster.

We have the data stored in an RDS Postgres 12.2 database.

`Sequel::Postgres.supports_streaming?` returns true

Our code is something like this:

```ruby
Sequel.connect('postgres://postgres:xxxxxxxxxx:5432/postgres?search_path=x') do |db|
  db.extension(:pg_streaming)
  db[:table].stream.each do |row|
    ...
  end
end
```

But it waits for about 30 seconds, and returns:

```
PG::Error: cannot set single row mode
```

Maybe there's some timeout or something happening? Or maybe I misunderstood how this feature works.

Interestingly if we change the code to:

```ruby
Sequel.connect('postgres://postgres:xxxxxxxxxx:5432/postgres?search_path=x') do |db|
  db.extension(:pg_streaming)
  db.stream_all_queries = true
  db[:table].first
end
```

It raises in exception on the `db[:table].first` line with:

```
PG::UnableToSend: another command is already in progress
```

The following code:

```ruby
Sequel.connect('postgres://postgres:xxxxxxxxxx:5432/postgres?search_path=x') do |db|
  db.extension(:pg_streaming)
  db[:table].first
end
```

Works correctly and `db[:table].first` returns the first row in the database.

We are using:

- sequel (5.32.0)
- sequel_pg (1.13.0)
- pg (1.2.3)

**Comment by jeremyevans** [comment] 2020-05-06 14:53
Maybe there is something specific to RDS that causes it not to work?  On standard PostgreSQL it works fine:

```ruby
Sequel.connect('postgres:///?user=sequel_test') do |db|
  db.server_version           # 120002
  db.create_table(:table) do
    primary_key :id
    String :name
  end
  db[:table].import([:name], [['A'], ['B']])
end

Sequel.connect('postgres:///?user=sequel_test') do |db|
  db.extension(:pg_streaming)
  db.stream_all_queries = true
  db[:table].first             # {:id=>1, :name=>"A"}
end
```

Can you recreate this problem on a standard PostgreSQL instance?

**Comment by ollym** [comment] 2020-05-06 15:24
hey @jeremyevans I created a fresh RDS instance and created the table with id and name column as above.

Going to put the credentials here in the name of science, not much you can do with it either way, but it does look like an RDS issue. Not sure where to start searching for to debug this. Any ideas where to start?

```ruby
Sequel.connect('postgres://postgres:postgres1234@test-db.coemsdyfeklc.us-east-1.rds.amazonaws.com:5432/postgres') do |db|
  db.extension(:pg_streaming)
  db.stream_all_queries = true
  db[:table].first
end
```

**Comment by jeremyevans** [comment] 2020-05-06 15:39
No ideas, it's probably due to differences between RDS and standard PostgreSQL.  You could try posting a bug for RDS PostgreSQL (assuming they have a public bugtracker).

If you want to try debugging it yourself, you'll want to drop down to a lower level.  I would recommend writing a reproducer in C using libpq directly, and testing it against both RDS and standard PostgreSQL to see what the differences are.

In terms of workarounds, you can try using `paged_each` instead of streaming:

```ruby
db[:table].paged_each do |row|
  #
end
```

This will use a cursor that pulls down 1000 rows at a time by default.

I'm going to close this now as it doesn't appear to be a bug in sequel_pg.

**Closed by jeremyevans** 2020-05-06 15:39 UTC
